### ISSUE TITLE
hosting at heroku

### ISSUE THREAD

**Issue by NucsuM** [hcrudolph/osm4kids-backend#6]
Lets host this project at https://www.heroku.com free pricing.

**Comment by hcrudolph** [comment]
Successfully running with f5572e52839feb18095c7d3bb12325d2387cbd3e.

However, this is not itegrated with GitHub, yet. For now, I'll `git push heroku master` the current version when we want it running on Heroku.

**Comment by hcrudolph** [comment]
Starting with 3833e9d61513870b96e54e33a3f5539838f6626c, successful builds will automatically be deployed on Heroku by Travis CI.
